services:
  zabbix-postgres:
    image: postgres:latest
    container_name: zabbix-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - zabbix_postgres_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 10s
      retries: 5

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_ENABLE_SNMP_TRAPS: ${ZBX_ENABLE_SNMP_TRAPS}
    networks:
      - ${NETWORK}
    ports:
      - "10051:10051"
    depends_on:
      zabbix-postgres:
        condition: service_healthy

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: always
    environment:
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PHP_TZ: ${PHP_TZ}
    networks:
      - ${NETWORK}
    ports:
      - "80:8080"
    depends_on:
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: always
    privileged: true
    networks:
      - ${NETWORK}
    depends_on:
      - zabbix-server
      - zabbix-web

networks:
  zabbix:
    external: true

volumes:
  zabbix_postgres_data:
    driver: local
  zabbix_server_data:
    driver: local
  zabbix_web_data:
    driver: local
